version: "3"

tasks:
  build:
    desc: "Build application"
    cmds:
      - "swift build -c release --arch arm64 --arch x86_64"
  run:
    desc: "Run application"
    cmds:
      - "swift run otto {{.CLI_ARGS}}"
  clean:
    desc: "Clean build artifacts"
    cmds:
      - "swift package clean"
  update:
    desc: "Update packages"
    cmds:
      - "swift package update"
